name: Keep Render Backend Awake

# Every 50 minutes, plus allow manual runs
on:
  schedule:
    - cron:  '*/55 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /health endpoint
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://cv-parser-llama.onrender.com/health)
          echo "Render health check returned HTTP $STATUS"